apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: 192.168.56.11/web/nginx:v1.1
        ports:
        - containerPort: 80
        command: ["nginx"]
      imagePullSecrets:
        - name: harbor-secret
