apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
       # command: ["mysql"]
      - name: nginx
        image: 192.168.56.11/web/nginx:v1.2
        ports:
        - containerPort: 80
        command: ["nginx"]
      imagePullSecrets:
        - name: harbor-secret
