apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-master
  namespace: default
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "docker-volume"
    readOnly: false

